import streamlit as st
import openai
import requests
import os

st.set_page_config(page_title="AIMM - AI Income Machine", layout="wide")
st.title("🤖 AIMM - Autonomous Income Maximization Machine")

# Input API keys
openai_key = st.sidebar.text_input("🔑 OpenAI API Key", type="password")
zapier_webhook = st.sidebar.text_input("🌐 Zapier Webhook URL", type="password")

# Setup state
if "idea" not in st.session_state:
    st.session_state.idea = ""
if "image_url" not in st.session_state:
    st.session_state.image_url = ""

# Button 1: Generate Idea
if st.button("💡 Generate Business Idea"):
    openai.api_key = openai_key
    with st.spinner("Thinking of an idea..."):
        response = openai.ChatCompletion.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": "You are an expert AI that creates profitable, fast-launching business ideas for digital or AI-automated businesses."},
                {"role": "user", "content": "Give me a new business idea."}
            ]
        )
        st.session_state.idea = response.choices[0].message["content"]
    st.success("Idea generated!")

# Show idea
if st.session_state.idea:
    st.subheader("💡 Business Idea")
    st.write(st.session_state.idea)

# Button 2: Generate Image
if st.session_state.idea and st.button("🎨 Create DALL·E Branding Image"):
    openai.api_key = openai_key
    with st.spinner("Creating image..."):
        response = openai.Image.create(
            prompt=f"Brand logo or illustration for: {st.session_state.idea}",
            n=1,
            size="512x512"
        )
        st.session_state.image_url = response['data'][0]['url']
    st.success("Image created!")

# Show image
if st.session_state.image_url:
    st.image(st.session_state.image_url, caption="Generated by DALL·E 3")

# Button 3: Send to Zapier
if st.session_state.idea and st.session_state.image_url and st.button("🚀 Automate with Zapier"):
    if zapier_webhook:
        payload = {
            "idea": st.session_state.idea,
            "image_url": st.session_state.image_url
        }
        response = requests.post(zapier_webhook, json=payload)
        if response.status_code == 200:
            st.success("📤 Sent to Zapier!")
        else:
            st.error("❌ Zapier failed.")
    else:
        st.warning("⚠️ Please enter a Zapier Webhook URL.")